import {isAI} from './players.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url,body){const r=await fetch('/api/'+url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const v=await r.json();if(!r.ok)throw Error(v.error||'Error del servidor');return v;}
export let account=null;try{account=(await api('me')).user;}catch{}
export function bindMatch(s,game,machine=false){if(machine&&!s.players.some(p=>p.controller))s.players[1].controller={type:'ai',level:'medium'};const ownerSeat=s.players.findIndex((p,i)=>!isAI(s,i));s.accountMatch={id:crypto.randomUUID(),owner:ownerSeat>=0?account?.id||null:null,ownerSeat,game,mode:s.players.some((p,i)=>isAI(s,i))?'machine':s.players.length===1?'solo':'local'};s.machine=s.players.some((p,i)=>isAI(s,i));if(account&&ownerSeat>=0)s.players[ownerSeat].name=account.name;return s;}
const inflight=new Set();
export async function recordMatch(s,scores){const m=s.accountMatch;if(!m?.owner||inflight.has(m.id))return;inflight.add(m.id);try{const pending=JSON.parse(localStorage.getItem('mesa-results-pending')||'{}');pending[m.id]={...m,players:[s.accountMatch.ownerSeat??0,...s.players.map((_,i)=>i).filter(i=>i!==(s.accountMatch.ownerSeat??0))].map(i=>({name:s.players[i].name,score:scores[i]}))};localStorage.setItem('mesa-results-pending',JSON.stringify(pending));await flush();}finally{inflight.delete(m.id);}}
async function flush(){if(!account)return;const pending=JSON.parse(localStorage.getItem('mesa-results-pending')||'{}');for(const [id,m]of Object.entries(pending)){if(m.owner!==account.id)continue;try{await api('matches',m);delete pending[id];}catch{break;}}localStorage.setItem('mesa-results-pending',JSON.stringify(pending));}
export function accountLink(){return `<a class="account-link" href="/profile.html">${account?'👤 '+esc(account.name):'Ingresar / Registrarse'}</a>`;}

flush().catch(()=>{});window.addEventListener('online',()=>flush().catch(()=>{}));
if(document.querySelector('#profile'))show();
async function show(){const el=document.querySelector('#profile');
 if(!account){el.innerHTML=`<h1>Tu lugar en Mesa Abierta</h1><p>Guardá tus récords y los resultados de tus partidas. La cuenta corresponde al primer jugador; los demás juegan como invitados.</p><form><label>Usuario<input name="name" required minlength="3" maxlength="24" autocomplete="username"></label><label>Contraseña<input name="password" type="password" required minlength="10" maxlength="128" autocomplete="current-password"></label><label>Código de recuperación <small>Solo para recuperar tu cuenta</small><input name="recovery" autocomplete="off"></label><div class="actions"><button name="action" value="login">Ingresar</button><button name="action" value="register">Crear cuenta</button><button name="action" value="recover">Recuperar cuenta</button></div><p role="status" id="status"></p></form>`;
 el.querySelector('form').onsubmit=async e=>{e.preventDefault();const action=e.submitter.value,status=el.querySelector('#status');try{const f=new FormData(e.target),v=await api(action,Object.fromEntries(f));account=v.user;if(v.recovery){el.innerHTML=`<h1>Guardá tu código de recuperación</h1><p>Permite recuperar la cuenta sin correo electrónico. Guardalo en un lugar privado; no podremos mostrártelo otra vez.</p><textarea readonly aria-label="Código de recuperación">${esc(v.recovery)}</textarea><button id="continue">Ya lo guardé</button>`;el.querySelector('#continue').onclick=()=>location.reload();}else location.reload();}catch(err){status.textContent=err.message;}};return;}
 el.innerHTML='<p>Cargando historial…</p>';try{await flush();const data=await api('history'),filter=new URLSearchParams(location.search).get('game'),matches=data.matches.filter(m=>!filter||m.game===filter),best={};for(const m of matches){const key=m.game+' · '+m.mode;best[key]=Math.max(best[key]??0,m.players[0].score);}
 el.innerHTML=`<h1>Hola, ${esc(account.name)}</h1><div class="actions"><a href="/">Jugar</a><button id="logout">Cerrar sesión</button></div><h2>Tus mejores puntuaciones</h2><div class="records">${Object.entries(best).map(([k,v])=>`<article><strong>${v} puntos</strong><p>${esc(k.replace('machine','contra máquina').replace('local','humanos locales').replace('solo','solitario'))}</p></article>`).join('')||'<p>Todavía no terminaste partidas con esta cuenta.</p>'}</div><h2>Historial de partidas</h2>${matches.map(m=>`<article><h3>${esc(m.game)} · ${esc(m.mode==='machine'?'Contra máquina':m.mode==='solo'?'Solitario':'Humanos locales')}</h3><small>${new Date(m.date).toLocaleString('es-UY')}</small><ul>${m.players.map((p,i)=>`<li>${esc(p.name)}${i?' (rival / invitado)':''}: <b>${p.score} puntos</b></li>`).join('')}</ul></article>`).join('')}<p>Resultados personales de partidas locales. No constituyen una clasificación competitiva verificada.</p>`;el.querySelector('#logout').onclick=async()=>{await api('logout',{});location.reload();};}catch(e){el.textContent=e.message;}
}

export async function renderGameHistory(host,game){
 if(!host)return;host.classList.add('game-history');host.innerHTML='<p role="status">Cargando tu recorrido…</p>';
 const link=`/profile.html?game=${encodeURIComponent(game)}`;
 try{const response=await fetch('/api/history');if(!host.isConnected)return;if(response.status===401){host.innerHTML=`<div class="gh-heading"><div><small>TU RECORRIDO</small><h2>Cada partida cuenta</h2></div><span class="gh-emblem" aria-hidden="true">♜</span></div><p>Iniciá sesión antes de comenzar una partida para guardar tus puntos y descubrir tus mejores resultados.</p><a class="gh-link" href="${link}">Ingresar y ver mi historial →</a>`;return;}if(!response.ok)throw Error();const data=await response.json();if(!host.isConnected)return;const matches=data.matches.filter(m=>m.game===game),best=matches.length?Math.max(...matches.map(m=>m.players[0].score)):null,modes={solo:'Solitario',local:'Humanos locales',machine:'Contra máquina'};
 host.innerHTML=`<div class="gh-heading"><div><small>TU RECORRIDO</small><h2>Tu mesa, tus logros</h2></div><a class="gh-link" href="${link}">Ver historial →</a></div><div class="gh-stats"><div><span>Mejor puntuación</span><strong>${best??'—'}<small>${best===null?'':' pts'}</small></strong></div><div><span>Partidas terminadas</span><strong>${matches.length}</strong></div></div>${matches.length?`<h3>Últimas partidas</h3><div class="gh-recent">${matches.slice(0,3).map(m=>`<div><span><b>${esc(modes[m.mode]||m.mode)}</b><small>${new Date(m.date).toLocaleDateString('es-UY')}</small></span><strong>${m.players[0].score} <small>pts</small></strong></div>`).join('')}</div><p class="gh-note">Consultá el historial para ver todos los participantes y los récords por modalidad.</p>`:'<p class="gh-empty">Tu próximo desafío puede ser tu primer récord.<br>Terminá una partida con tu cuenta para verla acá.</p>'}`;
 }catch{if(host.isConnected)host.innerHTML='<p>No pudimos cargar tus resultados.</p><button class="gh-link" type="button">Reintentar</button>';host.querySelector('button')?.addEventListener('click',()=>renderGameHistory(host,game));}
}
