import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,act,validateSave,validateCatalog,ingredient,placementError,burgerInfo,requirements,finalScores} from './burger-engine.js';
import {CATALOG,VERIFIED_ORDERS} from './burger-data.js';
// Synthetic fixtures test rules only; they are not a playable retail deck.
const food=(name,type,tags,next='any',perfect=false)=>({name,type,tags,next,perfect});
const foods=[food('Beef Patty','meat',['Meat','Patty']),food('Veggie Patty','meat',['Patty']),food('Fried Egg','cheese',[]),food('Cheddar Cheese','cheese',['Cheese']),food('Pickles','salad',['Salad']),food('Tomato','salad',['Salad']),food('Mustard','sauce',['Sauce']),food('BBQ Sauce','sauce',['Sauce']),food('Middle Bun','bun',[]),food('Roasted Pepper','salad',['Salad'],'any',true),food('Bacon','meat',['Meat']),food('Avocado','salad',['Salad'],'any',true)];
const fixture={id:'TEST-ONLY',complete:true,cards:Array.from({length:72},(_,i)=>({id:`c${i}`,sides:[foods[i%12],foods[(i+1)%12]]})),orders:Array.from({length:21},(_,i)=>({id:`o${i}`,name:`Test ${i}`,checks:[{kind:'tag',value:'Patty',count:1}]}))};
const fresh=(n=2,first=0)=>createGame(Array.from({length:n},(_,i)=>`Chef ${i}`),{catalog:fixture,seed:42,first});
const go=(s,a)=>act(s,a,fixture);
const piece=(i,side=0)=>({id:`c${i}`,side});
// Controlled scenarios move real fixture IDs out of all other zones.
function arrange(s,{hand=[],stacks=[[],[]]}={}){const p=s.players[s.current],ids=new Set([...hand,...stacks.flat().map(x=>x.id)]);const returned=[...p.hand,...p.burgers.flat().map(x=>x.id)];p.hand=[];p.burgers=[[],[]];s.deck.push(...returned);s.deck=s.deck.filter(id=>!ids.has(id));s.discard=s.discard.filter(id=>!ids.has(id));s.market=s.market.map(id=>ids.has(id)?null:id);for(const q of s.players){q.hand=q.hand.filter(id=>!ids.has(id));q.burgers=q.burgers.map(stack=>stack.filter(x=>!ids.has(x.id)));}p.hand=hand;p.burgers=stacks;return s;}
test('catálogo incompleto bloquea partidas; no se inventa un mazo comercial',()=>{assert.throws(()=>createGame(['A','B']),/catálogo/);assert.equal(CATALOG.cards.length,0);assert.throws(()=>validateCatalog({...fixture,cards:fixture.cards.slice(1)}));});
test('preparación 2/3/4: 12/14/18 pedidos y conservación de todas las cartas',()=>{for(const n of [2,3,4]){const s=fresh(n,n-1);assert.equal(s.orderDeck.length,{2:9,3:11,4:15}[n]);assert.equal(s.orders.length,3);assert(s.orders.every(x=>x.coins===1));assert(s.players.every(p=>p.hand.length===4&&p.coins===2));assert.equal(s.first,n-1);assert(validateSave(s,fixture));}});
test('compras cuestan $1; huecos no se reponen hasta limpieza; errores atómicos',()=>{let s=go(fresh(),{type:'ready'});s=go(s,{type:'buy',index:0});assert.equal(s.market[0],null);assert.equal(s.players[0].coins,1);const before=JSON.stringify(s);assert.throws(()=>go(s,{type:'buy',index:0}));assert.equal(JSON.stringify(s),before);s=go(s,{type:'buy',index:1});assert.throws(()=>go(s,{type:'buy',index:2}));s=go(go(go(s,{type:'advance'}),{type:'advance'}),{type:'advance'});assert(s.market.every(Boolean));assert.throws(()=>go(s,{type:'cleanup'}),/cuatro/);});
test('matriz de símbolos, pan comodín y orientación inválida',()=>{for(const type of ['meat','salad','cheese','sauce'])for(const target of ['meat','salad','cheese','sauce','bun']){const c={cards:[{id:'a',sides:[food('A','meat',[],type)]},{id:'b',sides:[food('B',target,[])]}]};assert.equal(placementError([{id:'a',side:0}],{id:'b',side:0},c)==='',target===type||target==='bun');}assert.throws(()=>ingredient(piece(0,2),fixture));});
test('tres colocaciones en total entre dos bases, cuatro solo tras mejora',()=>{for(const upgraded of [false,true]){let s=arrange(fresh(),{hand:['c0','c1','c2','c3','c4']});s.phase='build';s.players[0].upgraded=upgraded;const cap=upgraded?4:3;for(let i=0;i<cap;i++)s=go(s,{type:'place',id:`c${i}`,side:0,burger:i%2});assert.equal(s.placed,cap);assert.throws(()=>go(s,{type:'place',id:`c${cap}`,side:0,burger:0}));}});
test('espátula mueve un bloque sin reordenar ni gastar colocaciones; solo dos usos',()=>{let s=arrange(fresh(),{stacks:[[piece(0),piece(1),piece(2)],[]]});s.phase='build';s=go(s,{type:'spatula',burger:0,start:1,target:1});assert.deepEqual(s.players[0].burgers,[[piece(0)],[piece(1),piece(2)]]);assert.equal(s.placed,0);s=go(s,{type:'spatula',burger:1,start:0,target:'discard'});assert(s.discard.includes('c1'));assert.throws(()=>go(s,{type:'spatula',burger:0,start:0,target:1}));assert(validateSave(s,fixture));});
test('espátula no puede mover un bloque sobre un símbolo incompatible',()=>{const c=structuredClone(fixture);c.cards[0].sides[0].next='sauce';let s=arrange(fresh(),{stacks:[[piece(1)],[piece(0)]]});s.phase='build';assert.throws(()=>act(s,{type:'spatula',burger:0,start:0,target:1},c),/salsas/);assert.equal(s.players[0].spatulaUses,0);});
test('tamaños exactos 1–3/4–6/7–9/10+, sin contar panes',()=>{for(const [n,reward]of [[0,0],[1,1],[3,1],[4,3],[6,3],[7,5],[9,5],[10,10],[16,10]]){const stack=Array.from({length:n},()=>piece(0));stack.push(piece(8));assert.equal(burgerInfo(stack,fixture).reward,reward);assert.equal(burgerInfo(stack,fixture).count,n);}});
test('vegetariano por palabras clave: medallón vegetal no es carne; tipos no son etiquetas',()=>{const o=VERIFIED_ORDERS.find(x=>x.id==='vegetarian-cowboy');assert(requirements([piece(1),piece(7)],o,fixture).every(x=>x.ok));assert(requirements([piece(0),piece(1),piece(7)],o,fixture).some(x=>!x.ok));assert.equal(requirements([piece(2)],{checks:[{kind:'tag',value:'Cheese',count:1}]},fixture).at(-1).ok,false);});
test('ingredientes diferentes, top exacto, límites, igualdad y sin panes solos',()=>{assert.equal(requirements([piece(4),piece(4)],{checks:[{kind:'distinct',value:'Salad',count:2}]},fixture).at(-1).ok,false);assert(requirements([piece(4),piece(5)],{checks:[{kind:'distinct',value:'Salad',count:2}]},fixture).every(x=>x.ok));const sunny=VERIFIED_ORDERS.find(x=>x.id==='sunny');assert(requirements([piece(0),piece(3),piece(4),piece(2)],sunny,fixture).every(x=>x.ok));assert(requirements([piece(0),piece(3),piece(4),piece(2),piece(8)],sunny,fixture).some(x=>!x.ok));assert.equal(requirements([piece(8)],{checks:[{kind:'without',value:'Meat'}]},fixture)[0].ok,false);assert(requirements([piece(0),piece(3),piece(4),piece(6)],VERIFIED_ORDERS.find(x=>x.id==='even'),fixture).every(x=>x.ok));});
test('venta única: tamaño + monedas acumuladas + perfectos y reposición inmediata',()=>{let s=arrange(fresh(),{stacks:[[piece(0),piece(9)],[]]});s.phase='score';const order=s.orders[0].id;s.orders[0].coins=4;s=go(s,{type:'score',burger:0,order,reward:'coins'});assert.equal(s.players[0].coins,8);assert.deepEqual(s.lastScore,{player:0,earned:6,size:1,waiting:4,perfect:1,upgrade:false,order:fixture.orders.find(x=>x.id===order).name});assert.equal(s.phase,'cleanup');assert.deepEqual(s.orders.map(x=>x.coins),[1,2,2]);assert.throws(()=>go(s,{type:'score',burger:0,order:s.orders[1].id,reward:'coins'}));assert(validateSave(s,fixture));});
test('mejora reemplaza solo los $10, conserva pedido/perfectos y la otra hamburguesa',()=>{let s=arrange(fresh(),{stacks:[Array.from({length:10},(_,i)=>piece(i)),[piece(10)]]});s.players[0].burgers[0].push(piece(11));s.deck=s.deck.filter(x=>x!=='c11');s.discard=s.discard.filter(x=>x!=='c11');for(const p of s.players)p.hand=p.hand.filter(x=>x!=='c11');s.market=s.market.map(x=>x==='c11'?null:x);s.phase='score';s=go(s,{type:'score',burger:0,order:s.orders[0].id,reward:'upgrade'});assert.equal(s.players[0].upgraded,true);assert.equal(s.lastScore.size,0);assert.equal(s.players[0].burgers[1].length,1);assert.equal(s.players[0].coins,5);});
test('limpieza repone mercado antes del descarte y recicla sin duplicar',()=>{let s=fresh();s.phase='score';s.discard=[...s.deck];s.deck=[];const old=s.players[0].hand.slice();s.market[0]=null; // Move removed market card back to supply first in a separate valid scenario.
 const valid=arrange(fresh(),{hand:old});valid.phase='score';valid.discard=valid.deck;valid.deck=[];const x=valid.market[0];valid.market[0]=null;valid.discard.push(x);s=go(valid,{type:'advance'});assert(s.market[0]);assert(!old.includes(s.market[0]));s=go(s,{type:'cleanup',discard:old});assert.equal(s.players[0].hand.length,4);assert(validateSave(s,fixture));});
test('mazo vacío con tres pedidos no termina; falta de reposición sí, sin turno extra',()=>{for(const first of [0,1,2]){let s=arrange(fresh(3,first),{stacks:[[piece(0)],[]]});s.retiredOrders.push(...s.orderDeck);s.orderDeck=[];s.phase='score';assert.equal(s.ending,false);s=go(s,{type:'score',burger:0,order:s.orders[0].id,reward:'coins'});assert(s.ending);s=go(s,{type:'cleanup'});for(let i=0;i<2;i++){s=go(s,{type:'ready'});for(let j=0;j<3;j++)s=go(s,{type:'advance'});s=go(s,{type:'cleanup'});}assert.equal(s.phase,'over');assert(s.players.every(p=>p.turns===1));assert.throws(()=>go(s,{type:'ready'}));assert(validateSave(s,fixture));}});
test('desempate de mayoría no da bonus; empate final comparte puntuación',()=>{const s=fresh();s.players[0].completed=['a'];s.players[1].completed=['b'];assert.deepEqual(finalScores(s).map(x=>x.total),[6,6]);s.players[0].completed.push('c');s.players[0].spatulaUses=2;assert.deepEqual(finalScores(s).map(x=>x.total),[7,6]);});
test('60 partidas sintéticas completas: fases, conservación, recarga y final para 2–4',()=>{for(const n of [2,3,4])for(let seed=1;seed<=20;seed++){let s=createGame(Array.from({length:n},(_,i)=>`P${i}`),{catalog:fixture,seed,first:seed%n});let turns=0;while(s.phase!=='over'&&turns++<400){s=go(s,{type:'ready'});s=go(s,{type:'advance'});let p=s.players[s.current];for(const id of [...p.hand].slice(0,3)){const side=fixture.cards.find(c=>c.id===id).sides.findIndex(x=>x.tags.includes('Patty'));s=go(s,{type:'place',burger:0,id,side:side<0?0:side});}s=go(s,{type:'advance'});p=s.players[s.current];const order=s.orders.find(o=>requirements(p.burgers[0],fixture.orders.find(x=>x.id===o.id),fixture).every(x=>x.ok));s=order?go(s,{type:'score',burger:0,order:order.id,reward:'coins'}):go(s,{type:'advance'});s=go(s,{type:'cleanup',discard:[...s.players[s.current].hand]});assert(validateSave(s,fixture));s=JSON.parse(JSON.stringify(s));}assert.equal(s.phase,'over');assert(s.players.every(p=>p.turns===s.players[0].turns));}});
