import {EXAMPLES,TYPES,RULEBOOK,VERIFIED_ORDERS} from './burger-data.js';
import {placementError,burgerInfo,requirements} from './burger-engine.js';
const app=document.querySelector('#burger');
const catalog={cards:EXAMPLES};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let stack=[],sides=EXAMPLES.map(()=>0),selected=2,notice='',phase=0,orderIndex=0;
const steps=[
 ['01','Mercado','Comprá los ingredientes que te faltan.','Cada carta cuesta $1. Podés comprar varias, pero los espacios vacíos recién se reponen al comenzar la limpieza.'],
 ['02','Construcción','Cada ingrediente prepara el siguiente.','Colocá hasta 3 cartas, repartidas como quieras entre tus dos hamburguesas. Girá cada carta antes de colocarla y hacé coincidir su tipo con el símbolo que pide la anterior.'],
 ['03','Burger Up!','Un pedido listo, una hamburguesa vendida.','Podés vender una sola hamburguesa por turno. Debe cumplir todos los requisitos de un pedido y tener al menos un ingrediente. Los panes no cuentan para su tamaño.'],
 ['04','Limpieza','Prepará tu mano para el próximo turno.','Primero se repone el mercado. Después podés descartar cartas y robás hasta tener 4. Si tenés más de 4, debés descartar. Al agotarse los ingredientes se mezcla el descarte.'],
];
function art(kind,large=false){
 const shapes={
  meat:'<path d="M22 65Q25 36 100 37T178 65L170 78Q100 101 30 78Z" fill="#76402b"/><path d="M45 53l12 24M72 46l15 36M107 46l15 35M140 51l13 26" stroke="#3c2b21" stroke-width="7" stroke-linecap="round"/>',
  salad:'<path d="M21 64Q29 40 44 53Q48 26 68 43Q89 16 103 39Q126 19 138 43Q162 29 167 54Q191 48 178 71Q157 90 141 74Q118 94 103 77Q82 96 65 76Q43 91 21 64Z" fill="#6b963d"/><path d="M41 63Q101 44 161 65" fill="none" stroke="#b4ce72" stroke-width="5"/>',
  cheese:'<path d="M24 45L145 32L183 65L73 94Z" fill="#e7ac2f"/><path d="M24 45L73 77L183 65L73 94L24 61Z" fill="#ca8520"/><circle cx="110" cy="53" r="7" fill="#f5d46c"/><circle cx="78" cy="61" r="4" fill="#f5d46c"/>',
  sauce:'<path d="M25 64Q42 36 63 58T103 57T142 55T177 59" stroke="#d74831" fill="none" stroke-width="14" stroke-linecap="round"/>',
  bun:'<path d="M22 68C22 3 178 3 178 68Z" fill="#dc9d48"/><path d="M22 69Q100 82 178 69" stroke="#b57530" stroke-width="10" stroke-linecap="round"/><g stroke="#f8e6b5" stroke-width="4" stroke-linecap="round"><path d="M58 37l5 3M89 27l4 4M123 32l4-3M147 47l3 3M94 50l5-1"/></g>',
 };
 return `<svg class="food-art ${large?'large':''}" viewBox="0 0 200 110" aria-hidden="true">${shapes[kind]||shapes.bun}</svg>`;
}
function heroBurger(){return `<div class="hero-burger" aria-hidden="true">${art('bun')}${art('salad')}${art('cheese')}${art('meat')}${art('sauce')}<div class="bottom-bun"></div><div class="plate"></div></div>`;}
function card(i){const x=EXAMPLES[i],side=sides[i],s=x.sides[side],other=x.sides[1-side],used=stack.some(p=>p.id===x.id),error=placementError(stack,{id:x.id,side},catalog);return `<article class="ingredient ${selected===i?'selected':''} ${used?'used':''}" style="--type:${TYPES[s.type].color}"><button class="card-face" data-select="${i}" ${used?'disabled':''} aria-pressed="${selected===i}" aria-label="Seleccionar ${esc(s.label)}"><div class="card-heading"><span>${TYPES[s.type].icon} ${TYPES[s.type].name}</span>${s.perfect?'<b title="Perfecto: suma $1 adicional al vender">+$1</b>':''}</div><h3>${esc(s.label)}</h3>${art(s.type)}<div class="next">Después pide <b>${TYPES[s.next].icon} ${TYPES[s.next].name}</b></div><div class="alternate">Otra mitad: ${esc(other.label)}</div></button><button class="rotate" data-flip="${i}" ${used?'disabled':''}>↻ Girar carta</button><small>${used?'Ya colocada: su orientación queda fija.':error||'✓ Puede colocarse ahora'}</small></article>`;}
const ruleWords={'Beef Patty':'medallón de carne','Grilled Chicken':'pollo grillado','BBQ Sauce':'salsa barbacoa','Veggie Patty':'medallón vegetal','Fried Egg':'huevo frito','Avocado':'palta','Pineapple':'ananá','Pickles':'pepinillos','Bacon':'panceta','Salad':'vegetales','Meat':'carne','Sauce':'salsas','Cheese':'queso','Patty':'medallones'};
const ruleText=text=>text.replace(/Beef Patty|Grilled Chicken|BBQ Sauce|Veggie Patty|Fried Egg|Avocado|Pineapple|Pickles|Bacon|Salad|Meat|Sauce|Cheese|Patty/g,word=>ruleWords[word]);
function orderPanel(){
 const order=VERIFIED_ORDERS[orderIndex],checks=requirements(stack,order,catalog),info=burgerInfo(stack,catalog),ready=checks.every(x=>x.ok);
 return `<section class="order-practice"><div><span class="eyebrow">APRENDÉ A LEER UN PEDIDO</span><h2>¿Qué le falta a tu hamburguesa?</h2><p>Elegí un pedido real y compará sus requisitos con tu construcción. Estas tres cartas de ejemplo no alcanzan para completar todos los pedidos.</p><label for="practice-order">Pedido de referencia</label><select id="practice-order">${VERIFIED_ORDERS.map((o,i)=>`<option value="${i}" ${i===orderIndex?'selected':''}>${esc(o.name)}</option>`).join('')}</select><ul class="requirements">${checks.map(x=>`<li class="${x.ok?'met':'missing'}"><span aria-hidden="true">${x.ok?'✓':'○'}</span> <span class="sr-only">${x.ok?'Cumplido:':'Pendiente:'}</span>${esc(ruleText(x.text))}</li>`).join('')}</ul><strong>${ready?'Cumple los requisitos.':'Todavía faltan requisitos.'}</strong></div><aside><span class="eyebrow">SI PUDIERAS VENDERLA</span><h3>La cuenta, paso a paso.</h3><dl><div><dt>Tamaño · ${info.tier}</dt><dd>$${info.reward}</dd></div><div><dt>Ingredientes perfectos</dt><dd>$${info.perfect}</dd></div><div><dt>Monedas sobre el pedido</dt><dd>Variable</dd></div></dl><p>Las monedas del pedido se agregan a esta suma. Aquí no se simulan rondas ni ventas: no se otorgan puntos.</p></aside></section>`;
}
function render(){const available=EXAMPLES.filter(x=>!stack.some(p=>p.id===x.id)),choice=EXAMPLES[selected],canPlace=choice&&!stack.some(p=>p.id===choice.id)&&!placementError(stack,{id:choice.id,side:sides[selected]},catalog),info=burgerInfo(stack,catalog),last=stack.length?EXAMPLES.find(x=>x.id===stack.at(-1).id).sides[stack.at(-1).side]:null;
 app.innerHTML=`<section class="hero"><div><span class="eyebrow">INGREDIENTES, ESTRATEGIA Y UN POCO DE HAMBRE</span><h1>Burger <em>Up!</em></h1><p class="lead">Tu próxima gran idea<br>lleva pan, queso y estrategia.</p><p>Armá hamburguesas por capas, completá pedidos<br>y hacé crecer tu restaurante.</p><div class="pills"><span>2–4 personas</span><span>Mesa compartida</span><span>Guía paso a paso</span></div><a class="primary" href="#practice">Probar cómo se colocan las cartas ↓</a></div><div class="hero-visual">${heroBurger()}<span class="stamp">HECHO<br><b>CAPA A CAPA</b></span></div></section>
 <aside class="preparing"><span class="status-dot"></span><div><strong>La partida completa está en preparación.</strong><p>Esta práctica usa tres cartas verificadas del reglamento. Todavía falta completar el mazo del juego; la práctica no guarda puntos ni récords.</p></div><span class="status-label">VISTA PREVIA</span></aside>
 <section id="guide"><div class="section-title"><div><span class="eyebrow">UN TURNO EN CUATRO PASOS</span><h2>Aprendé el ritmo de la cocina.</h2></div><a href="${RULEBOOK}" target="_blank" rel="noopener">Reglamento v2 en inglés ↗</a></div><div class="phase-tabs" role="tablist" aria-label="Fases del turno">${steps.map((s,i)=>`<button role="tab" id="tab-${i}" aria-controls="phase-content" aria-selected="${phase===i}" data-phase="${i}"><small>${s[0]}</small>${s[1]}</button>`).join('')}</div><div class="phase-content" id="phase-content" role="tabpanel" aria-labelledby="tab-${phase}"><h3>${steps[phase][2]}</h3><p>${steps[phase][3]}</p></div></section>
 <section id="practice"><div class="section-title"><div><span class="eyebrow">PRÁCTICA DE COLOCACIÓN</span><h2>Primero, una buena base.</h2></div><button class="quiet" data-reset>Reiniciar práctica ↻</button></div><div class="practice-layout"><div class="kitchen"><div class="kitchen-label"><span>TU HAMBURGUESA</span><span>${info.count} ${info.count===1?'ingrediente':'ingredientes'}</span></div><div class="burger-stack">${stack.slice().reverse().map(p=>{const s=EXAMPLES.find(x=>x.id===p.id).sides[p.side];return `<div class="layer" style="--type:${TYPES[s.type].color}">${art(s.type)}<span>${esc(s.label)}${s.perfect?' · perfecto':''}</span></div>`;}).join('')}<div class="base"><div class="bottom-bun"></div><span>Pan base · acepta cualquier tipo</span></div></div><div class="kitchen-bottom">${last?`La siguiente carta debe ser: <b>${TYPES[last.next].icon} ${TYPES[last.next].name}</b>`:'Elegí una carta de abajo y colocala sobre el pan.'}</div></div><aside class="coach"><span class="eyebrow">TU AYUDANTE DE COCINA</span><h3>${stack.length>=2?'Ya construiste dos capas.':stack.length?'Seguí el símbolo.':'Empezá por el cheddar.'}</h3><p>${stack.length>=2?'Cada carta conserva la mitad que elegiste. En una partida disponés de otra hamburguesa donde empezar una combinación diferente.':stack.length?`La última carta pide ${TYPES[last.next].name.toLowerCase()}. Podés seleccionar otra carta o girar una que todavía esté en tu mano para buscar ese tipo.`:'Seleccioná el queso cheddar y colocalo sobre el pan. Después buscá una carta que coincida con el símbolo que pide.'}</p><button class="primary" data-place ${canPlace?'':'disabled'}>Colocar ${choice?esc(choice.sides[sides[selected]].label):'ingrediente'} →</button><p class="feedback" role="status">${esc(notice||(!canPlace&&choice?(stack.some(p=>p.id===choice.id)?'Elegí otra carta de tu mano.':placementError(stack,{id:choice.id,side:sides[selected]},catalog)):''))}</p><div class="tip">Girar elige la otra mitad de una carta. Una vez colocada, ya no se puede girar.</div></aside></div><div class="hand-heading"><h3>Tu mano de ejemplo</h3><small>${available.length} ${available.length===1?'carta disponible':'cartas disponibles'} · Ilustración propia de referencia</small></div><div class="hand">${EXAMPLES.map((_,i)=>card(i)).join('')}</div></section>
 ${orderPanel()}<section class="reference"><div><span class="eyebrow">DE SÁNDWICH A COLOSAL</span><h2>Más capas, más recompensa.</h2><p>Al vender sumás la recompensa por tamaño, las monedas del pedido y $1 por cada ingrediente perfecto. Los panes no cuentan para el tamaño.</p></div><div class="sizes">${[['1–3','Sándwich','$1'],['4–6','Gourmet','$3'],['7–9','Torre','$5'],['10+','Colosal','$10 o mejora']].map(([n,t,v])=>`<article><strong>${n}</strong><span>${t}</span><b>${v}</b></article>`).join('')}</div></section>
 <section class="faq"><h2>Pequeños detalles, grandes hamburguesas.</h2>${[
 ['¿Qué hace la espátula?','Durante construcción podés mover una carta junto con todas las que tiene encima a tu otra hamburguesa o al descarte. Conservan su orden y orientación. El bloque debe encajar en su nuevo destino. La espátula se usa como máximo dos veces.'],
 ['¿Para qué sirve el pan del medio?','Es un comodín: puede colocarse sobre cualquier tipo y permite colocar después cualquier tipo. No cuenta como ingrediente al calcular el tamaño de la hamburguesa.'],
 ['¿Cómo mejoro mi restaurante?','Al vender una Colosal podés elegir mejorar en vez de cobrar los $10 por tamaño. Seguís recibiendo las monedas del pedido y de ingredientes perfectos. En los próximos turnos podés colocar hasta 4 cartas; la mano se repone hasta 4 igualmente.'],
 ['¿Cómo termina la partida?','Cuando ya no se puede reponer un pedido, se termina la ronda en curso. El primer jugador no vuelve a jugar. Cada $1 vale un punto; la espátula aporta 4, 2 o 0 según sus usos. Quien haya completado más pedidos gana 5 puntos adicionales; si esa mayoría está empatada, nadie recibe el bonus.'],
 ].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</section><footer><span>Diseño del juego: Matt Parkes · Rule & Make</span><span>Adaptación en desarrollo · Referencia: reglamento v2</span></footer>`;
}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const scrollY=window.scrollY;if(b.hasAttribute('data-phase'))phase=+b.dataset.phase;else if(b.hasAttribute('data-select')){selected=+b.dataset.select;notice='';}else if(b.hasAttribute('data-flip')){const i=+b.dataset.flip;sides[i]=1-sides[i];selected=i;notice='';}else if(b.hasAttribute('data-reset')){stack=[];sides=EXAMPLES.map(()=>0);selected=2;notice='Práctica reiniciada.';}else if(b.hasAttribute('data-place')){const p={id:EXAMPLES[selected].id,side:sides[selected]},error=placementError(stack,p,catalog);if(error)notice=error;else{stack.push(p);notice='Carta colocada. Su orientación queda fija.';const remaining=EXAMPLES.map((x,i)=>({x,i})).filter(({x})=>!stack.some(p=>p.id===x.id));const next=remaining.find(({x,i})=>!placementError(stack,{id:x.id,side:sides[i]},catalog))||remaining[0];selected=next?.i??0;}}render();window.scrollTo(0,scrollY);const focus=b.hasAttribute('data-phase')?app.querySelector(`[data-phase="${phase}"]`):app.querySelector('[data-place]');if(focus&&!focus.disabled)focus.focus({preventScroll:true});});
app.addEventListener('change',e=>{if(e.target.id==='practice-order'){orderIndex=Number(e.target.value);const y=window.scrollY;render();window.scrollTo(0,y);app.querySelector('#practice-order').focus({preventScroll:true});}});
render();
