import {CARDS,OBJECTIVES} from './naturalis-data.js';
export const card=id=>CARDS.find(c=>c.id===id);
export const offsets=[[-1,1],[1,1],[1,-1],[-1,-1]];
const check=(v,m)=>{if(!v)throw Error(m);};
export function symbols(p){const counts={};p.board.forEach((t,i)=>{const c=card(t.id);if(t.back)c.center.forEach(v=>counts[v]=(counts[v]||0)+1);(t.back?c.back:c.front).forEach((v,k)=>{if(v&&!p.board.slice(i+1).some(a=>a.x===t.x+offsets[k][0]&&a.y===t.y+offsets[k][1]))counts[v]=(counts[v]||0)+1;});});return counts;}
export function spaces(p){const out=new Map();for(const t of p.board)for(const [dx,dy]of offsets){const x=t.x+dx,y=t.y+dy;if(!p.board.some(a=>a.x===x&&a.y===y))out.set(x+','+y,[x,y]);}return [...out.values()];}
export function reason(p,id,back,x,y){if(!Number.isInteger(x)||!Number.isInteger(y))return 'Posición inválida.';if(p.board.some(t=>t.x===x&&t.y===y))return 'Ese lugar está ocupado.';let covered=0;for(const t of p.board){const k=offsets.findIndex(([dx,dy])=>t.x+dx===x&&t.y+dy===y);if(k<0)continue;covered++;const c=card(t.id);if((t.back?c.back:c.front)[k]===null)return 'No podés cubrir una esquina cerrada.';}if(!covered)return 'La carta debe cubrir al menos una esquina.';const c=card(id);if(!c)return 'Carta desconocida.';if(!back&&c.kind==='gold'){const have=symbols(p),need={};for(const v of c.need)need[v]=(need[v]||0)+1;for(const v in need)if((have[v]||0)<need[v])return 'Faltan recursos visibles para esta carta de oro. Podés jugar su reverso.';}return '';}
function shuffle(a,rng){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function createNaturalis(names,rng=Math.random){check(names.length>=2&&names.length<=4,'Elegí entre 2 y 4 jugadores.');const resource=shuffle(CARDS.filter(c=>c.kind==='resource').map(c=>c.id),rng),gold=shuffle(CARDS.filter(c=>c.kind==='gold').map(c=>c.id),rng),starters=shuffle(CARDS.filter(c=>c.kind==='starter').map(c=>c.id),rng),objectives=shuffle(OBJECTIVES.map(o=>o.id),rng);const common=[objectives.pop(),objectives.pop()],players=names.map(name=>({name,hand:[resource.pop(),resource.pop(),gold.pop()],board:[{id:starters.pop(),x:0,y:0,back:false}],options:[objectives.pop(),objectives.pop()],secret:null,score:0}));return {version:1,players,resource,gold,market:{resource:[resource.pop(),resource.pop()],gold:[gold.pop(),gold.pop()]},common,first:Math.floor(rng()*names.length),turn:0,tick:0,endAt:null,phase:'privacy',setup:true,log:[]};}
export function objectiveScore(p,id){const o=OBJECTIVES.find(o=>o.id===id),have=symbols(p);if(o.resources){const need={};o.resources.forEach(v=>need[v]=(need[v]||0)+1);return Math.min(...Object.keys(need).map(v=>Math.floor((have[v]||0)/need[v])))*o.points;}
 const patterns=[];for(const t of p.board){const [ox,oy]=o.pattern[0],indices=o.pattern.map(([dx,dy,col])=>p.board.findIndex(a=>a.x===t.x+dx-ox&&a.y===t.y+dy-oy&&card(a.id).color===col));if(indices.every(i=>i>=0))patterns.push(indices);}
 // Maximum disjoint occurrences: greedy counting can undercount intersecting patterns.
 const memo=new Map();function best(i,used){if(i===patterns.length)return 0;const key=i+':'+used.toString();if(memo.has(key))return memo.get(key);const mask=patterns[i].reduce((m,k)=>m|(1n<<BigInt(k)),0n);const n=Math.max(best(i+1,used),(used&mask)?0:1+best(i+1,used|mask));memo.set(key,n);return n;}return best(0,0n)*o.points;}
function finish(s){s.results=s.players.map(p=>{const objectives=[...s.common,p.secret].map(id=>({id,points:objectiveScore(p,id)})),bonus=objectives.reduce((n,o)=>n+o.points,0);return {total:p.score+bonus,bonus,objectives};});const max=Math.max(...s.results.map(r=>r.total)),tie=Math.max(...s.results.filter(r=>r.total===max).map(r=>r.bonus));s.winners=s.results.flatMap((r,i)=>r.total===max&&r.bonus===tie?[i]:[]);s.phase='over';}
export function actNaturalis(state,a){const s=structuredClone(state),p=s.players[s.turn];check(s.phase!=='over','La partida terminó.');switch(a.type){
 case'ready':check(s.phase==='privacy','No corresponde.');s.phase=s.setup?'prepare':'place';break;
 case'prepare':check(s.phase==='prepare'&&p.options.includes(a.secret),'Elegí un objetivo.');p.secret=a.secret;p.options=[];p.board[0].back=!!a.back;s.turn++;if(s.turn===s.players.length){s.setup=false;s.turn=s.first;}s.phase='privacy';break;
 case'place':{check(s.phase==='place'&&p.hand.includes(a.id),'Elegí una carta de tu mano.');check(typeof a.back==='boolean','Elegí una cara.');const why=reason(p,a.id,a.back,a.x,a.y);check(!why,why);const covered=p.board.filter(t=>Math.abs(t.x-a.x)===1&&Math.abs(t.y-a.y)===1).length;p.hand.splice(p.hand.indexOf(a.id),1);p.board.push({id:a.id,x:a.x,y:a.y,back:a.back});const c=card(a.id),points=a.back?0:c.scoring==='corners'?covered*2:c.scoring==='objects'?(symbols(p)[c.object]||0):c.points;p.score+=points;s.log.unshift(`${p.name} obtuvo ${points} puntos al colocar una carta.`);if(p.score>=20&&s.endAt===null)s.endAt=(Math.floor(s.tick/s.players.length)+2)*s.players.length;s.phase='draw';break;}
 case'draw':{check(s.phase==='draw','Primero colocá una carta.');if(a.kind){check(['resource','gold'].includes(a.kind),'Mazo inválido.');if(a.index===-1){check(s[a.kind].length,'Mazo agotado.');p.hand.push(s[a.kind].pop());}else{check([0,1].includes(a.index)&&s.market[a.kind][a.index]!==null,'Carta no disponible.');p.hand.push(s.market[a.kind][a.index]);s.market[a.kind][a.index]=s[a.kind].pop()??null;}}else check(!s.resource.length&&!s.gold.length&&Object.values(s.market).flat().every(x=>x===null),'Elegí una carta disponible.');if(!s.resource.length&&!s.gold.length&&s.endAt===null)s.endAt=(Math.floor(s.tick/s.players.length)+2)*s.players.length;s.tick++;if(s.endAt!==null&&s.tick>=s.endAt)finish(s);else{s.turn=(s.turn+1)%s.players.length;s.phase='privacy';}break;}
 default:throw Error('Acción desconocida.');}return s;}
