import test from 'node:test';import assert from 'node:assert/strict';
import {CARDS,OBJECTIVES} from './naturalis-data.js';
import {createNaturalis,actNaturalis,spaces,reason,symbols,objectiveScore} from './naturalis-engine.js';
test('catálogo completo y preparación sin cartas duplicadas',()=>{assert.equal(CARDS.filter(c=>c.kind==='resource').length,40);assert.equal(CARDS.filter(c=>c.kind==='gold').length,40);assert.equal(CARDS.filter(c=>c.kind==='starter').length,6);assert.equal(OBJECTIVES.length,16);const s=createNaturalis(['A','B','C','D']);const ids=[...s.resource,...s.gold,...Object.values(s.market).flat(),...s.players.flatMap(p=>p.hand)];assert.equal(ids.length,80);assert.equal(new Set(ids).size,80);});
test('cubrir símbolos los retira; recursos centrales del reverso permanecen',()=>{const p={board:[{id:0,x:0,y:0,back:true}]};assert.equal(symbols(p).FUNGI,1);p.board.push({id:1,x:1,y:1,back:true});assert.equal(symbols(p).FUNGI,2);});
test('esquinas cerradas bloquean; el oro se comprueba antes de colocar',()=>{const p={board:[{id:0,x:0,y:0,back:false}]};assert.match(reason(p,1,true,1,-1),/cerrada/);const gold=CARDS.find(c=>c.kind==='gold');assert.match(reason(p,gold.id,false,-1,1),/recursos/);assert.equal(reason(p,gold.id,true,-1,1),'');});
test('conjuntos de objetivos cuentan repeticiones completas',()=>{const p={board:Array.from({length:7},(_,i)=>({id:0,x:i*4,y:0,back:true}))};assert.equal(objectiveScore(p,94),4);});
test('20 puntos completa la ronda y una adicional, sin finalizar inmediatamente',()=>{let s=createNaturalis(['A','B']);s.setup=false;s.turn=s.first;s.phase='place';s.players[s.turn].score=20;const p=s.players[s.turn];const [x,y]=spaces(p).find(([x,y])=>!reason(p,p.hand[0],true,x,y));s=actNaturalis(s,{type:'place',id:p.hand[0],back:true,x,y});assert.equal(s.endAt,4);assert.equal(s.phase,'draw');});
test('partidas completas de 2, 3 y 4 jugadores, guardado y conservación de cartas',()=>{for(const n of [2,3,4]){let s=createNaturalis(Array.from({length:n},(_,i)=>'P'+i)),steps=0;while(s.phase!=='over'&&steps++<1000){const p=s.players[s.turn];if(s.phase==='privacy')s=actNaturalis(s,{type:'ready'});else if(s.phase==='prepare')s=actNaturalis(s,{type:'prepare',secret:p.options[0],back:true});else if(s.phase==='place'){const id=p.hand[0],[x,y]=spaces(p).find(([x,y])=>!reason(p,id,true,x,y));s=actNaturalis(s,{type:'place',id,back:true,x,y});}else{let choice;for(const kind of ['resource','gold']){if(s[kind].length){choice={type:'draw',kind,index:-1};break;}const index=s.market[kind].findIndex(v=>v!==null);if(index>=0){choice={type:'draw',kind,index};break;}}s=actNaturalis(s,choice||{type:'draw'});}s=JSON.parse(JSON.stringify(s));}assert.equal(s.phase,'over');assert(s.results.every(r=>r.total>=0));const all=[...s.resource,...s.gold,...Object.values(s.market).flat().filter(v=>v!==null),...s.players.flatMap(p=>[...p.hand,...p.board.filter(t=>t.id<80).map(t=>t.id)])];assert.equal(all.length,80);assert.equal(new Set(all).size,80);}});
