import test from 'node:test';
import assert from 'node:assert/strict';
import {useMovementAbility,dive,resumeAbility} from './survive-abilities.js';
import {chooseAttack,respondRepellent} from './survive-creatures.js';
const fixture=()=>({turn:0,turnNumber:3,phase:'action',moves:3,swum:['p'],players:[{abilities:[{id:'d',effect:'dolphin',acquiredTurn:1},{id:'v',effect:'dive',acquiredTurn:1}]}],cells:{a:{terrain:'water',neighbors:['b']},b:{terrain:'water',neighbors:['a','c']},c:{terrain:'rescue',neighbors:['b']},empty:{terrain:'water',neighbors:[]}},adventurers:[{id:'p',owner:0,status:'active',cell:'a',raft:null}],creatures:[{id:'c',type:'shark',cell:'empty'}],rafts:[],pending:null});
test('delfín permite dos pasos extra sin gastar ni reiniciar los movimientos normales',()=>{const s=fixture(),n=useMovementAbility(s,'d','p',['b','c']);assert.equal(n.adventurers[0].status,'rescued');assert.equal(n.moves,3);assert.deepEqual(n.swum,['p']);assert.equal(s.players[0].abilities.length,2);});
test('delfín no inicia en tierra ni atraviesa tierra para volver al agua',()=>{const s=fixture();s.cells.a.terrain='beach';assert.throws(()=>useMovementAbility(s,'d','p',['b']),/nadadores/);s.cells.a.terrain='water';s.cells.b.terrain='beach';assert.throws(()=>useMovementAbility(s,'d','p',['b','c']),/termina/);});
test('buceo requiere agua vacía y una habilidad de un turno anterior',()=>{const s=fixture();assert.throws(()=>dive(s,'v','c','a'),/vacío/);const n=dive(s,'v','c','b');assert.equal(n.creatures[0].cell,'b');assert.equal(n.players[0].abilities.length,1);s.players[0].abilities[1].acquiredTurn=3;assert.throws(()=>dive(s,'v','c','b'),/todavía/);});
test('un delfín puede completar el segundo paso tras repeler un tiburón',()=>{const s=fixture();s.creatures[0].cell='b';s.players[0].abilities.push({id:'rep',effect:'repellent'});let n=useMovementAbility(s,'d','p',['b','c']);assert.equal(n.pending.type,'attacks');n=respondRepellent(chooseAttack(n,'c'),0,'rep');assert.equal(n.pending.type,'ability-resume');n=resumeAbility(n);assert.equal(n.adventurers[0].status,'rescued');assert.equal(n.moves,3);assert.deepEqual(n.swum,['p']);});
