import {createSurvive,actSurvive,legalActions,decisionOwner,COLORS,restoreSurvive} from './survive-engine.js';
import {chooseSurvive} from './survive-bot.js';
import {cellName} from './survive-board.js';
import {RULEBOOK,TERRAIN} from './survive-data.js';
import {seatFields,configureSeats,isAI,controller} from './players.js';
import {accountLink,bindMatch,recordMatch,renderGameHistory} from './accounts.js';
const app=document.querySelector('#survive'),KEY='mesa-survive-v1';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const LABEL={beach:'Playa',forest:'Bosque',mountain:'Montaña',water:'Agua',rescue:'Refugio',volcano:'Volcán',serpent:'Serpiente',shark:'Tiburón',kaiju:'Kaiju',raft:'Balsa',paddles:'Remos',dolphin:'Delfín',dive:'Buceo',die:'Dado extra',repellent:'Repelente'};
const ICON={beach:'·',forest:'♣',mountain:'▲',water:'',rescue:'⚑',volcano:'♨',serpent:'🐉',shark:'🦈',kaiju:'🦖',raft:'▤',paddles:'⇉',dolphin:'🐬',dive:'↓',die:'⚄',repellent:'✋'};
const EXPLAIN={paddles:'Mové una balsa vacía o que controlás uno o dos espacios extra.',dolphin:'Mové a uno de tus nadadores uno o dos espacios extra. Puede terminar en tierra o en una balsa.',dive:'Trasladá una criatura del tablero a cualquier espacio de agua completamente vacío.',die:'Tirá el dado y mové una criatura. Al final del turno también tirarás el dado habitual.',repellent:'Cuando uno de tus aventureros comparte casilla con un tiburón o Kaiju, retiralo antes del ataque. Protege a todas las piezas de esa casilla.'};
let state=null,error='',viewer=null,selected=null,ability=null,inspected=null,privateOpen=false,screen='setup',aiTimer=null,actions=[],zoom=false,loadWarning='';
try{const raw=localStorage.getItem(KEY);if(raw){state=restoreSurvive(raw);}}catch{loadWarning='No pudimos recuperar el guardado anterior. Podés comenzar una nueva partida.';}
const button=(text,action,extra='')=>`<button data-ui="${action}" ${extra}>${text}</button>`;
function header(){return `<header><a href="/">▦ Mesa Abierta</a><nav>${button('Reglas y ayuda','rules','class="quiet"')}${accountLink()}</nav></header>`;}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{error='El navegador no pudo guardar. No cierres la pestaña hasta terminar.';}if(state.phase==='finished')recordMatch(state,state.results).catch(()=>{});}
function setup(){screen='setup';clearTimeout(aiTimer);app.innerHTML=header()+`<main class="landing"><section class="intro"><div><span class="eyebrow">LA COLECCIÓN / 05</span><h1>Survive<br><em>the Island</em></h1><p>La isla se hunde. El mar no perdona.<br>Salvá a tu expedición antes del tercer volcán.</p><div class="legend"><span>2–5 participantes</span><span>Personas + IA</span><span>Edición base 2024</span></div></div><div class="intro-art" aria-hidden="true"><span>🌋</span></div></section>${loadWarning?`<p class="notice">${esc(loadWarning)}</p>`:''}${state?button(state.phase==='finished'?'Ver último resultado':'Continuar partida guardada','resume','class="primary"'):''}<section id="survive-history"></section><form class="panel" id="new-game"><span class="eyebrow">PREPARAR LA EXPEDICIÓN</span><h2>¿Quién se anima a escapar?</h2><p>Elegí personas e inteligencias artificiales en cualquier asiento. Con dos participantes, cada uno controla 20 aventureros y coloca 4 balsas. Con tres a cinco, son 10 aventureros y 2 balsas por persona.</p><label>Participantes<select id="count">${[2,3,4,5].map(n=>`<option>${n}</option>`).join('')}</select></label><div class="setup-grid" id="seats"></div>${state&&state.phase!=='finished'?'<p class="notice">Una nueva partida reemplaza el guardado de Survive de este navegador.</p>':''}<p>Antes de colocar cada aventurero podrás ver su tesoro. Después quedará oculto: recordá dónde están los más valiosos.</p><button class="primary">Preparar la isla →</button><p id="setup-error" role="alert"></p></form><footer>Adaptación independiente de Survive the Island (2024), Julian Courtland-Smith · Zygomatic. Tablero e ilustraciones esquemáticos. Sin expansiones.</footer></main>`;
 renderGameHistory(document.querySelector('#survive-history'),'survive');
 const f=document.querySelector('#new-game'),seats=()=>{document.querySelector('#seats').innerHTML=Array.from({length:+f.querySelector('#count').value},(_,i)=>`<section class="seat-form"><h3>Asiento ${i+1}</h3><label>Nombre<input name="name" maxlength="18" required value="Jugador ${i+1}"></label>${seatFields(i)}<label>Color<select name="color">${['Coral','Amarillo','Azul','Violeta','Naranja'].map((name,c)=>`<option value="${c}" ${c===i?'selected':''}>${name}</option>`).join('')}</select></label></section>`).join('');};f.querySelector('#count').onchange=seats;seats();
 f.onsubmit=e=>{e.preventDefault();try{const n=createSurvive([...f.querySelectorAll('[name=name]')].map(x=>x.value.trim()||'Jugador'),{colors:[...f.querySelectorAll('[name=color]')].map(x=>+x.value)});configureSeats(n,f);n.players.forEach(p=>p.name=p.name.slice(0,24));bindMatch(n,'survive');state=n;viewer=null;selected=null;ability=null;inspected=null;error='';persist();render();}catch(e){document.querySelector('#setup-error').textContent=e.message;}};
}
function entity(id){return state.adventurers.find(p=>p.id===id)||state.rafts.find(r=>r.id===id)||state.creatures.find(c=>c.id===id);}
function entityName(id){const p=entity(id);if(!p)return id;if(p.owner!==undefined)return `${state.players[p.owner].name} · ${p.number}`;return p.type?`${LABEL[p.type]} ${+id.replace(/\D/g,'')+1}`:`Balsa ${+id.slice(1)+1}`;}
function filtered(){return actions.filter(a=>ability?a.tile===ability:a.type!=='ability-move'&&a.type!=='ability-die'&&a.type!=='dive').filter(a=>!a.id||selected===a.id||!['setup-person','move','creature','push-person','push-creature','ability-move','dive'].includes(a.type));}
function board(){
 const can=viewer===decisionOwner(state)&&!isAI(state,decisionOwner(state)),targets=new Set(can?filtered().map(a=>a.to||a.path?.at(-1)).filter(Boolean):[]);
 const polygons=Object.values(state.cells).map(c=>{const x=34+c.x*48,y=33+c.r*42,pts=Array.from({length:6},(_,i)=>{const angle=(60*i-30)*Math.PI/180;return `${x+27*Math.cos(angle)},${y+27*Math.sin(angle)}`;}).join(' '),ppl=state.adventurers.filter(a=>a.cell===c.id&&a.status==='active'),rafts=state.rafts.filter(r=>r.cell===c.id),creatures=state.creatures.filter(a=>a.cell===c.id);return `<g class="cell ${targets.has(c.id)?'target':''} ${inspected===c.id?'inspected':''}" tabindex="0" role="button" aria-label="${cellName(c.id)}, ${LABEL[c.terrain]}, ${ppl.length} aventureros${rafts.length?', balsa':''}${creatures.map(x=>', '+LABEL[x.type]).join('')}" data-ui="cell" data-cell="${c.id}"><polygon class="hex ${c.terrain}" points="${pts}"/><text class="tile-label" x="${x}" y="${y-16}" text-anchor="middle">${cellName(c.id)}</text>${!ppl.length&&!creatures.length&&!rafts.length?`<text class="terrain-icon" x="${x}" y="${y+8}" text-anchor="middle">${ICON[c.terrain]}</text>`:''}${rafts.length?`<rect x="${x-18}" y="${y-7}" width="36" height="21" rx="4" fill="#b78b59" stroke="#f5d296"/><path d="M${x-12},${y-5}v17m12,-17v17m12,-17v17" stroke="#775637"/>`:''}${ppl.slice(0,4).map((a,i)=>`<circle cx="${x+(i%2?8:-8)}" cy="${y+(i<2?-3:10)}" r="6" fill="${COLORS[a.color]}" stroke="#fff5cf" stroke-width="1.2"/>`).join('')}${ppl.length>4?`<text x="${x+18}" y="${y+19}" fill="white" font-size="9">+${ppl.length-4}</text>`:''}${creatures.map((a,i)=>`<text x="${x+i*10-(creatures.length-1)*5}" y="${y+9}" font-size="22" text-anchor="middle">${ICON[a.type]}</text>`).join('')}</g>`;}).join('');
 return `<div class="sea-wrap ${zoom?'zoomed':''}"><div class="sea-toolbar"><span>LA ISLA · ${Object.values(state.cells).filter(c=>TERRAIN.includes(c.terrain)).length} losetas</span><span>Volcanes <b>${state.volcanoes} / 3</b></span></div><div class="board-scroll"><svg class="board" viewBox="0 0 600 570" aria-label="Mesa compartida de Survive the Island">${polygons}</svg></div><p class="board-note">Tocá una casilla para ver sus piezas. Los bordes dorados señalan destinos disponibles. ${button(zoom?'Alejar':'Ampliar','zoom')}</p></div><div class="legend"><span>· Playa</span><span>♣ Bosque</span><span>▲ Montaña</span><span>⚑ Refugio</span><span>▤ Balsa</span><span>🐉 Serpiente</span><span>🦈 Tiburón</span><span>🦖 Kaiju</span></div>`;
}
function actionText(a){const route=a.path?.map(cellName).join(' → ');switch(a.type){case 'destroy-raft':return `Destruir ${entityName(a.id)}`;case 'resume-ability':return 'Completar el recorrido de la habilidad';case 'setup-person':return `Colocar en ${cellName(a.to)}`;case 'setup-raft':return `Balsa en ${cellName(a.to)}`;case 'move':return `Mover a ${cellName(a.to)}`;case 'sink':return `Hundir ${cellName(a.to)}`;case 'end-action':return 'Terminar movimientos →';case 'roll':return 'Tirar el dado de criaturas';case 'creature':case 'push-creature':return `Mover por ${route}`;case 'push-person':return `Empujar a ${cellName(a.to)}`;case 'ability-move':return `Recorrer ${route}`;case 'dive':return `Bucear a ${cellName(a.to)}`;case 'ability-die':return 'Usar dado extra';case 'spawn':return `Colocar ${entityName(a.id)}`;case 'attack':return `Resolver ${entityName(a.id)}`;case 'repel':return a.tile?'✋ Usar repelente':'No usar repelente';case 'resolve':return 'Aplicar el efecto';case 'board':return `Embarcar: ${a.ids.map(entityName).join(', ')}`;default:return a.type;}}
function guideText(){const p=state.pending;if(p){return {'ability-resume':['Continuar la habilidad','Resuelta la interacción, completá el segundo paso si la pieza todavía puede hacerlo.'],boarding:['Elegí quién sube','Hay más nadadores que plazas. Elegí la combinación que embarca.'],spawn:['Una pieza aparece','Elegí la pieza que se coloca en la casilla hundida. Si se agotó la reserva, podés recolocar una disponible.'],attacks:['Elegí el orden','Resolvé una criatura por vez. Antes del ataque, los afectados pueden responder con repelente.'],attack:p.responders.length?['¿Usás un repelente?','El repelente retira la criatura y protege a todos en la casilla, también a los rivales.']:['Resolver el ataque','Confirmá para aplicar el efecto de la criatura.'], 'kaiju-push':['El Kaiju abre camino','Elegí qué aventurero o criatura empujar primero y después su destino. Los aventureros avanzan una casilla; las criaturas usan su movimiento habitual.']}[p.type];}
 return {'setup-people':['Elegí un tesoro y su lugar','Seleccioná un aventurero de tu reserva y una loseta libre. Memorizá el valor: no podrás consultarlo durante la partida.'],'setup-rafts':['Prepará las balsas','Colocá una balsa en agua vacía junto a la isla. Las balsas son compartidas: se controlan por cantidad de pasajeros.'],action:['Guiá a tu expedición',`Quedan ${3-state.moves} movimientos normales. Elegí una pieza y su destino. Cada aventurero puede nadar una vez por turno; subir a una balsa con lugar es automático.`],sink:['La isla se hunde',`Retirá ${state.sinksRemaining} ${state.sinksRemaining===1?'loseta':'losetas'} del terreno más bajo disponible. Podés elegir cualquier loseta de ese tipo, incluso del interior.`],roll:['¿Qué acecha en el mar?','Tirá el dado. Si la criatura aparece en el tablero, tendrás que mover una de ese tipo.'],creature:[`Mové ${LABEL[state.roll]?.toLowerCase()}`,`${state.roll==='serpent'?'Un espacio de agua.':'Uno o dos espacios'+(state.roll==='shark'?' de agua.':' de agua o tierra.')} Se detiene al entrar en una casilla con la que interactúa.`]}[state.phase]||['Resolvé la mesa','Completá la decisión pendiente.'];
}
function guide(){const owner=decisionOwner(state),p=state.players[owner],ai=isAI(state,owner);if(ai)return `<aside class="panel guide"><span class="eyebrow">TURNO AUTOMÁTICO</span><h2>${esc(p.name)}</h2><p>La máquina está decidiendo su próxima acción.</p><p class="micro">Los tesoros y las habilidades privadas permanecen ocultos.</p>${error?`<p class="error" role="alert">${esc(error)}</p>${button('Reintentar','retry')}`:''}</aside>`;
 if(viewer!==owner)return `<aside class="panel guide"><span class="eyebrow">PASAR EL DISPOSITIVO</span><h2>${esc(p.name)}</h2><p>${state.pending?.responders?.length?'Te toca responder al ataque.':'Es tu momento de decidir.'} Los demás pueden seguir viendo el tablero; solo vos debés consultar tu información privada.</p>${button('Estoy listo/a','ready','class="primary"')}</aside>`;
 const [title,help]=guideText(),f=filtered(),list=f.filter(a=>!a.to&&!a.path||inspected===(a.to||a.path?.at(-1))),selectable=[...new Set(actions.filter(a=>ability?a.tile===ability:!a.tile).map(a=>a.id).filter(Boolean))].filter(id=>['setup-people','creature'].includes(state.phase)||entity(id)?.cell===inspected||selected===id||state.pending?.type==='kaiju-push');
 return `<aside class="panel guide"><div class="steps"><span class="${state.phase==='action'?'current':''}">1 Acción</span><span class="${state.phase==='sink'?'current':''}">2 Hundir</span><span class="${['roll','creature'].includes(state.phase)?'current':''}">3 Criaturas</span></div><span class="eyebrow">DECIDE ${esc(p.name)}</span><h2>${title}</h2><p>${help}</p>${error?`<p class="error" role="alert">${esc(error)}</p>`:''}${selected?`<p><b>${esc(entityName(selected))}</b> ${button('Cambiar','clear','class="quiet"')}</p>`:''}${selectable.length?`<div class="choice-list">${selectable.map(id=>{const x=entity(id);return button(`${x.owner!==undefined?`<span class="token-dot" style="--seat:${COLORS[x.color]}"></span>`:''}${esc(entityName(id))}${state.phase==='setup-people'?` · ${x.value} pts`:''}`,'select',`data-id="${id}" class="${selected===id?'selected':''}"`);}).join('')}</div>`:''}${inspected?`<p class="micro">${cellName(inspected)} · ${LABEL[state.cells[inspected].terrain]}</p>`:''}<div class="choice-list">${list.map(a=>`<button data-ui="act" data-index="${actions.indexOf(a)}" class="${['end-action','roll'].includes(a.type)?'primary':''}">${esc(actionText(a))}</button>`).join('')}</div>${!selected&&['action','creature'].includes(state.phase)?'<p class="micro">Tocá una casilla ocupada para elegir una pieza.</p>':''}${state.phase==='action'&&!state.pending?`<section class="private">${button(privateOpen?'Ocultar habilidades':`Consultar mis habilidades (${p.abilities.length})`,'private')}${privateOpen?`<div class="abilities">${p.abilities.map(t=>button(`${ICON[t.effect]} ${LABEL[t.effect]}`,'ability',`data-id="${t.id}" title="${EXPLAIN[t.effect]}" ${t.effect==='repellent'||t.acquiredTurn>=state.turnNumber?'disabled':''} class="${ability===t.id?'selected':''}"`)).join('')}</div>${ability?`<p>${EXPLAIN[p.abilities.find(t=>t.id===ability)?.effect]||''}</p>`:'<p class="micro">El repelente se ofrece automáticamente antes de un ataque. Las demás habilidades se usan desde un turno posterior.</p>'}`:''}</section>`:''}</aside>`;
}
function render(){const entering=screen!=='game',boardScroll=app.querySelector('.board-scroll'),scrollPos=boardScroll?{top:boardScroll.scrollTop,left:boardScroll.scrollLeft}:null;screen='game';clearTimeout(aiTimer);if(!state)return setup();
 if(state.phase==='finished'){app.innerHTML=header()+`<main class="landing"><span class="eyebrow">LA EXPEDICIÓN TERMINÓ</span><h1>${state.winners.length>1?'Victoria compartida':esc(state.players[state.winners[0]].name)+' ganó'}</h1><p>${state.endReason==='volcanoes'?'El tercer volcán puso fin a la partida.':'No quedan aventureros pendientes de rescate.'} Solo cuentan los tesoros que llegaron a un refugio.</p><div class="result-grid">${state.players.map((p,i)=>`<section class="panel" style="border-top:5px solid ${COLORS[p.color]}"><h2>${esc(p.name)}</h2><strong>${state.results[i]} <small>pts</small></strong><p>${state.adventurers.filter(a=>a.owner===i&&a.status==='rescued').length} aventureros rescatados</p><small>Tesoros: ${state.adventurers.filter(a=>a.owner===i&&a.status==='rescued').map(a=>a.value).join(' + ')||'ninguno'}</small></section>`).join('')}</div><div class="actions">${button('Preparar otra partida','setup','class="primary"')}<a href="/profile.html?game=survive">Mi historial y mejor puntuación →</a></div></main>`;persist();return;}
 actions=legalActions(state);app.innerHTML=header()+`<main><div class="topline"><div><span class="eyebrow">SURVIVE THE ISLAND · ${state.phase.startsWith('setup')?'PREPARACIÓN':'TURNO '+state.turnNumber}</span><h1>La última travesía</h1></div>${button('Salir al inicio','setup')}</div><div class="scores">${state.players.map((p,i)=>`<div class="score ${state.turn===i?'active':''}" style="--seat:${COLORS[p.color]}"><strong>${esc(p.name)}</strong><small>${state.adventurers.filter(a=>a.owner===i&&a.status==='rescued').length} a salvo · ${state.adventurers.filter(a=>a.owner===i&&['active','unplaced'].includes(a.status)).length} por salvar</small></div>`).join('')}</div><div class="game-layout"><section>${board()}</section>${guide()}</div><p class="status">Guardado automático en este navegador · Los tesoros se revelan al final.</p><details class="log"><summary>Registro de la partida</summary>${state.log.slice(0,12).map(l=>`<p>${esc(l)}</p>`).join('')}</details></main>`;
 if(entering)window.scrollTo({top:0});if(scrollPos){const el=app.querySelector('.board-scroll');if(el){el.scrollTop=scrollPos.top;el.scrollLeft=scrollPos.left;}}
 schedule();
}
function dispatch(a){const oldOwner=decisionOwner(state),oldTurn=state.turnNumber;try{state=actSurvive(state,a);error='';selected=null;ability=null;if(decisionOwner(state)!==oldOwner||state.turnNumber!==oldTurn){viewer=null;privateOpen=false;inspected=null;}persist();render();}catch(e){error=e.message;render();}}
function schedule(){if(screen!=='game'||state.phase==='finished'||!isAI(state,decisionOwner(state)))return;aiTimer=setTimeout(()=>{try{dispatch(chooseSurvive(state,controller(state,decisionOwner(state)).level));}catch(e){error='La máquina no pudo completar esta decisión: '+e.message;app.querySelector('.guide').insertAdjacentHTML('beforeend',`<p class="error">${esc(error)}</p>${button('Reintentar','retry')}`);}},450);}
function rules(){const d=document.createElement('dialog');d.className='help';d.innerHTML=`<span class="eyebrow">GUÍA DE LA EXPEDICIÓN</span><h2>Escapar con el tesoro</h2><p>Rescatá aventureros llevándolos a los refugios de las esquinas. Sus tesoros valen de 1 a 5, se memorizan durante la preparación y se suman al final.</p><ol><li><b>Acción:</b> hasta tres movimientos entre aventureros propios y balsas vacías o controladas. Cada paso consume uno. Un aventurero puede nadar una vez por turno; entrar o salir del agua cuenta como nadar. Tierra a balsa no cuenta.</li><li><b>Habilidades:</b> podés usar varias, además de tus movimientos. No podés usar una recién recibida hasta un turno posterior, salvo el repelente al responder un ataque.</li><li><b>Hundimiento:</b> elegí cualquier loseta del terreno más bajo: playa, bosque, montaña. Quienes estaban encima quedan en el agua. Si comenzaste el turno sin aventureros por rescatar, retirás dos.</li><li><b>Criaturas:</b> tirá el dado y mové una criatura de ese tipo. Serpiente: un espacio acuático, elimina aventureros y balsas. Tiburón: uno o dos de agua, elimina nadadores. Kaiju: uno o dos de agua o tierra, destruye balsas y empuja las demás piezas. Se detienen al interactuar.</li></ol><h3>Balsas compartidas</h3><p>Tres plazas. Podés mover una si tenés tantos o más pasajeros que cada rival; los empates permiten control compartido. Subir es automático si hay sitio. Cuando falta lugar, decide el jugador activo quién embarca.</p><h3>El final</h3><p>Termina inmediatamente al aparecer el tercer volcán o cuando todos los aventureros están rescatados o eliminados. Solo puntúan los rescatados. Un empate comparte la victoria.</p><h3>Habilidades</h3>${Object.entries(EXPLAIN).map(([k,v])=>`<p><b>${ICON[k]} ${LABEL[k]}:</b> ${v}</p>`).join('')}<details><summary>Caso especial: empuje sin salida</summary><p>Si un Kaiju obligaría a desplazar una criatura que no tiene ningún destino legal, ese movimiento no se permite. Por ejemplo, una serpiente rodeada completamente por tierra. El reglamento no detalla este caso: esta mesa aplica ese criterio para mantener las restricciones de movimiento.</p></details><p>Esta mesa usa un dibujo esquemático del tablero. Las IA son estrategias locales de tres niveles; no ven tesoros rivales, reversos de losetas ni habilidades ajenas.</p><p><a href="${RULEBOOK}" target="_blank" rel="noopener">Consultar el reglamento oficial en inglés ↗</a></p><button>Cerrar</button>`;document.body.append(d);d.querySelector('button').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();}
app.addEventListener('click',e=>{const b=e.target.closest('[data-ui]');if(!b||b.disabled)return;const ui=b.dataset.ui;if(ui==='rules')return rules();if(ui==='setup')return setup();if(ui==='resume'){viewer=null;error='';return render();}if(ui==='zoom'){zoom=!zoom;return render();}if(ui==='retry'){error='';return render();}if(!state||isAI(state,decisionOwner(state)))return;if(ui==='ready'){viewer=decisionOwner(state);return render();}if(viewer!==decisionOwner(state))return;if(ui==='act')return dispatch(actions[+b.dataset.index]);if(ui==='select'){selected=b.dataset.id;inspected=null;}if(ui==='clear'){selected=null;ability=null;}if(ui==='private')privateOpen=!privateOpen;if(ui==='ability'){ability=ability===b.dataset.id?null:b.dataset.id;selected=null;inspected=null;}if(ui==='cell'){inspected=b.dataset.cell;const options=filtered().filter(a=>(a.to||a.path?.at(-1))===inspected);if(options.length===1)return dispatch(options[0]);}render();});
app.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.matches('g[data-ui]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
setup();
