import test from 'node:test';
import assert from 'node:assert/strict';
import {tiles,setupCounts,removableTiles,controlsRaft,swimmingMove,endReason,score} from './survive-data.js';
test('Survive 2024: catálogo completo de losetas por terreno y reverso',()=>{const all=tiles();assert.equal(all.length,40);assert.equal(new Set(all.map(t=>t.id)).size,40);assert.deepEqual(['beach','forest','mountain'].map(k=>all.filter(t=>t.terrain===k).length),[16,16,8]);assert.equal(all.filter(t=>t.effect==='volcano').length,4);assert.equal(all.filter(t=>t.ability).length,15);});
test('dos personas usan dos colores y veinte aventureros; cinco comparten losetas tras las primeras cuarenta',()=>{assert.deepEqual(setupCounts(2),{adventurersPerPlayer:20,colorsPerPlayer:2,raftsPerPlayer:4});assert.equal(setupCounts(5).adventurersPerPlayer*5,50);assert.throws(()=>setupCounts(1));});
test('hundimiento permite cualquier loseta del menor espesor, no solo la costa',()=>{let all=tiles();assert.equal(removableTiles(all).length,16);all=all.filter(t=>t.terrain!=='beach');assert.ok(removableTiles(all).every(t=>t.terrain==='forest'));assert.equal(removableTiles([]).length,0);});
test('control de balsas: vacías, mayoría y empate; un tercero sin pasajeros no controla',()=>{assert.equal(controlsRaft(0,[]),true);assert.equal(controlsRaft(0,[{owner:0},{owner:1}]),true);assert.equal(controlsRaft(2,[{owner:0},{owner:1}]),false);assert.equal(controlsRaft(0,[{owner:0},{owner:1},{owner:1}]),false);});
test('nadar se determina por cualquiera de los extremos; balsa a tierra es a pie',()=>{assert.equal(swimmingMove('water','raft'),true);assert.equal(swimmingMove('land','water'),true);assert.equal(swimmingMove('raft','land'),false);});
test('tercer volcán termina inmediatamente; puntúan solo rescatados',()=>{const people=[{owner:0,value:5,status:'rescued'},{owner:0,value:4,status:'raft'},{owner:1,value:5,status:'rescued'}];assert.equal(endReason(2,people),null);assert.equal(endReason(3,people),'volcanoes');assert.deepEqual(score(people,2),[5,5]);});
