import test from 'node:test';
import assert from 'node:assert/strict';
import {move,movementReason,resolveBoarding} from './survive-movement.js';
const fixture=()=>({phase:'action',turn:0,moves:0,swum:[],pending:null,cells:{a:{terrain:'beach',neighbors:['b']},b:{terrain:'water',neighbors:['a','c']},c:{terrain:'water',neighbors:['b','d']},d:{terrain:'rescue',neighbors:['c']}},adventurers:[{id:'p',owner:0,status:'active',value:5,cell:'a',raft:null}],rafts:[],creatures:[]});
test('natación: entrar al agua consume el único desplazamiento, sin mutar el estado anterior',()=>{const s=fixture(),next=move(s,{type:'adventurer',id:'p',to:'b'});assert.equal(s.moves,0);assert.deepEqual(next.swum,['p']);assert.match(movementReason(next,{type:'adventurer',id:'p',to:'a'}),/ya nadó/);});
test('caminar a una balsa no consume natación; la balsa puede moverse y luego desembarcar',()=>{let s=fixture();s.rafts=[{id:'r',cell:'b'}];s=move(s,{type:'adventurer',id:'p',to:'b'});assert.deepEqual(s.swum,[]);s=move(s,{type:'raft',id:'r',to:'c'});assert.equal(s.adventurers[0].cell,'c');s=move(s,{type:'adventurer',id:'p',to:'d'});assert.equal(s.adventurers[0].status,'rescued');assert.equal(s.moves,3);});
test('balsa llena: la casilla cuenta como agua para un nuevo aventurero',()=>{const s=fixture();s.rafts=[{id:'r',cell:'b'}];for(let i=0;i<3;i++)s.adventurers.push({id:'x'+i,owner:1,status:'active',cell:'b',raft:'r'});const next=move(s,{type:'adventurer',id:'p',to:'b'});assert.equal(next.adventurers[0].raft,null);assert.deepEqual(next.swum,['p']);});
test('embarque disputado exige elegir pasajeros y no permite seguir moviendo',()=>{const s=fixture();s.rafts=[{id:'r',cell:'b'}];s.adventurers=Array.from({length:4},(_,i)=>({id:'p'+i,owner:i%2,status:'active',cell:'c',raft:null}));const n=move(s,{type:'raft',id:'r',to:'c'});assert.equal(n.pending.type,'boarding');assert.throws(()=>resolveBoarding(n,['p0']));const resolved=resolveBoarding(n,['p1','p2','p3']);assert.equal(resolved.adventurers[0].raft,null);assert.equal(resolved.adventurers.filter(p=>p.raft).length,3);});
test('Kaiju y volcán bloquean entradas; una serpiente abre resolución antes de eliminar',()=>{const s=fixture();s.creatures=[{id:'k',type:'kaiju',cell:'b'}];assert.match(movementReason(s,{type:'adventurer',id:'p',to:'b'}),/Kaiju/);s.creatures=[{id:'ss',type:'serpent',cell:'b'}];const n=move(s,{type:'adventurer',id:'p',to:'b'});assert.equal(n.pending.type,'attacks');assert.equal(n.adventurers[0].status,'active');});
