import {test} from 'node:test';
import assert from 'node:assert/strict';
import {sinkTile,spawn} from './survive-sinking.js';
function state(effect='dolphin'){return {phase:'sink',turn:0,turnNumber:4,sinksRemaining:1,players:[{abilities:[]}],cells:{a:{terrain:'beach',neighbors:['b','c'],tile:{id:'tile',effect}},b:{terrain:'water',neighbors:['a']},c:{terrain:'forest',neighbors:['a'],tile:{effect:'raft'}}},adventurers:[{id:'p',owner:0,status:'active',cell:'a',raft:null,value:5}],rafts:[{id:'r',cell:null}],creatures:[{id:'s',type:'shark',cell:null}],pending:null};}
test('hundir convierte en agua y guarda la habilidad para otro turno sin alterar el original',()=>{const s=state(),n=sinkTile(s,'a');assert.equal(n.cells.a.terrain,'water');assert.equal(n.players[0].abilities[0].acquiredTurn,4);assert.equal(s.cells.a.terrain,'beach');assert.throws(()=>sinkTile(s,'c'));});
test('aparición de tiburón abre respuesta antes de eliminar',()=>{let n=sinkTile(state('shark'),'a');assert.equal(n.pending.type,'spawn');n=spawn(n,'s');assert.equal(n.pending.type,'attacks');assert.equal(n.adventurers[0].status,'active');});
test('remolino elimina solo centro y vecinos acuáticos',()=>{const s=state('whirlpool');s.adventurers.push({id:'safe',owner:0,status:'active',cell:'c'});s.rafts[0].cell='b';const n=sinkTile(s,'a');assert.equal(n.adventurers[0].status,'eliminated');assert.equal(n.adventurers[1].status,'active');assert.equal(n.rafts[0].cell,null);});
test('tercer volcán termina aun si resta un segundo hundimiento',()=>{const s=state('volcano');s.cells.a.terrain='mountain';s.cells.c.terrain='water';s.volcanoes=2;s.sinksRemaining=2;const n=sinkTile(s,'a');assert.equal(n.phase,'finished');assert.equal(n.endReason,'volcanoes');assert.equal(n.sinksRemaining,1);});
test('balsa agotada nunca roba una ocupada',()=>{const s=state('raft');s.rafts[0].cell='b';s.adventurers.push({id:'other',owner:0,status:'active',cell:'b',raft:'r'});const n=sinkTile(s,'a');assert.equal(n.pending,null);assert.equal(n.rafts[0].cell,'b');});
test('no aparece un tiburón en la casilla ocupada por un Kaiju',()=>{const s=state('shark');s.creatures.push({id:'k',type:'kaiju',cell:'a'});const n=sinkTile(s,'a');assert.equal(n.pending,null);assert.equal(n.creatures[0].cell,null);});
