import test from 'node:test';
import assert from 'node:assert/strict';
import {moveCreature,chooseAttack,respondRepellent,applyAttack,pushAdventurer,destroyRaft} from './survive-creatures.js';
const fixture=()=>({players:[{abilities:[{id:'rep',effect:'repellent'}]},{abilities:[]}],cells:{a:{terrain:'water',neighbors:['b']},b:{terrain:'water',neighbors:['a','c']},c:{terrain:'beach',neighbors:['b']}},creatures:[{id:'shark',type:'shark',cell:'a'}],rafts:[{id:'r',cell:'b'}],adventurers:[{id:'swimmer',owner:0,status:'active',cell:'b',raft:null,value:5},{id:'aboard',owner:1,status:'active',cell:'b',raft:'r',value:1}],pending:null});
test('tiburón se detiene en la primera interacción y no mata antes de ofrecer repelente',()=>{const s=fixture();assert.throws(()=>moveCreature(s,'shark',['b','a']),/detenerse/);let n=chooseAttack(moveCreature(s,'shark',['b']),'shark');assert.throws(()=>applyAttack(n),/repelente/);n=respondRepellent(n,0,'rep');assert.equal(n.creatures[0].cell,null);assert.ok(n.adventurers.every(a=>a.status==='active'));assert.equal(s.players[0].abilities.length,1);});
test('pasar repelente elimina solo nadadores, mantiene pasajeros y no revela valores',()=>{let n=chooseAttack(moveCreature(fixture(),'shark',['b']),'shark');n=applyAttack(respondRepellent(n,0));assert.equal(n.adventurers[0].status,'eliminated');assert.equal(n.adventurers[1].status,'active');assert.equal(n.rafts[0].cell,'b');assert.equal(n.pending,null);});
test('serpiente no admite repelente y elimina balsa y pasajeros',()=>{const s=fixture();s.creatures[0].type='serpent';const n=applyAttack(chooseAttack(moveCreature(s,'shark',['b']),'shark'));assert.ok(n.adventurers.every(a=>a.status==='eliminated'));assert.equal(n.rafts[0].cell,null);});
test('Kaiju destruye la balsa y espera decisiones individuales de empuje',()=>{const s=fixture();s.creatures[0].type='kaiju';let n=chooseAttack(moveCreature(s,'shark',['b']),'shark');n=applyAttack(respondRepellent(n,0));assert.equal(n.pending.type,'kaiju-push');assert.equal(n.rafts[0].cell,'b');n=destroyRaft(n,'r');assert.equal(n.rafts[0].cell,null);n=pushAdventurer(n,'swimmer','c');assert.equal(n.adventurers[0].cell,'c');assert.equal(n.pending.people.length,1);n=pushAdventurer(n,'aboard','a');assert.equal(n.pending,null);});
test('Kaiju no inicia un desplazamiento imposible de una serpiente cercada por tierra',()=>{const s=fixture();s.adventurers=[];s.rafts=[];s.cells.a.terrain='forest';s.creatures=[{id:'k',type:'kaiju',cell:'a'},{id:'ss',type:'serpent',cell:'b'}];assert.throws(()=>moveCreature(s,'k',['b']),/no puede completar/);assert.equal(s.creatures[0].cell,'a');});
